### ISSUE TITLE
Throwing  EXC_BAD_ACCESS (code=1, address=0x0) Swift doesn't seem to like what objc is sending

### ISSUE THREAD

**Issue by rhellman** [STMicroelectronics/BlueSTSDK_iOS#4]
Everything looks good until the return and dictionary is in swift.

https://github.com/STMicroelectronics/BlueSTSDK_iOS/blob/6cec1629334c9bcad369fc6b7ee51569486544d7/BlueSTSDK/BlueSTSDK/BlueSTSDKManager.swift#L39

**Comment by GiovanniVisentiniST** [comment]
Hi Rendy,

are you using Xcode 10.2?

could you try the last commit: 16d88d9aa1e595fe730aab867e81f0aff7ef327f
I rewrite the BoardFeatureMap class in swift to avoid problems.

Thanks
Giovanni

**Comment by rhellman** [comment]
Hi Giovanni,

Thank you for the quick response! I am using Xcode 10.2 and with the new commit everything looks great. 

Still not sure why the dictionary pointer from objc was bad and interested to know if you have any ideas but not a huge concern.

I had to make some minor changes but was able to get everything up and running in STBlueMS_iOS. Let me know if you want to to submit a pull request for STBlueMS_iOS. 

Best,
Randy

**Comment by GiovanniVisentiniST** [comment]
Hi Randy,

the pointer returned by objc was a pointer to a static dictionary, my idea about the error is that something change into the static initialization procedure ( or I didn't use the best practice to initialize a static object) 

ok for the pull request for STBlueMS, since I'm still developing the new version..
